//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTaxCalculator.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SalesTaxCalculator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TaxTabTitle {
            get {
                return ResourceManager.GetString("TaxTabTitle", resourceCulture);
            }
        }
        
        public static string RateTabTitle {
            get {
                return ResourceManager.GetString("RateTabTitle", resourceCulture);
            }
        }
        
        public static string ZipPlaceholder {
            get {
                return ResourceManager.GetString("ZipPlaceholder", resourceCulture);
            }
        }
        
        public static string CountryPlaceholder {
            get {
                return ResourceManager.GetString("CountryPlaceholder", resourceCulture);
            }
        }
        
        public static string CityPlaceholder {
            get {
                return ResourceManager.GetString("CityPlaceholder", resourceCulture);
            }
        }
        
        public static string CalculateRateButton {
            get {
                return ResourceManager.GetString("CalculateRateButton", resourceCulture);
            }
        }
        
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        public static string StateInvalidMessage {
            get {
                return ResourceManager.GetString("StateInvalidMessage", resourceCulture);
            }
        }
        
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        public static string ValidationFailedMessage {
            get {
                return ResourceManager.GetString("ValidationFailedMessage", resourceCulture);
            }
        }
        
        public static string ZipCodeInvalidMessage {
            get {
                return ResourceManager.GetString("ZipCodeInvalidMessage", resourceCulture);
            }
        }
        
        public static string CountryCodeInvalidMessage {
            get {
                return ResourceManager.GetString("CountryCodeInvalidMessage", resourceCulture);
            }
        }
        
        public static string InternetConnectionRequiredMessage {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredMessage", resourceCulture);
            }
        }
        
        public static string NumberInvalidMessage {
            get {
                return ResourceManager.GetString("NumberInvalidMessage", resourceCulture);
            }
        }
        
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        public static string CountryRateLabel {
            get {
                return ResourceManager.GetString("CountryRateLabel", resourceCulture);
            }
        }
        
        public static string CityRateLabel {
            get {
                return ResourceManager.GetString("CityRateLabel", resourceCulture);
            }
        }
        
        public static string CombinedDistrictRateLabel {
            get {
                return ResourceManager.GetString("CombinedDistrictRateLabel", resourceCulture);
            }
        }
        
        public static string CombinedRateLabel {
            get {
                return ResourceManager.GetString("CombinedRateLabel", resourceCulture);
            }
        }
        
        public static string StateRateLabel {
            get {
                return ResourceManager.GetString("StateRateLabel", resourceCulture);
            }
        }
        
        public static string FreightTaxableLabel {
            get {
                return ResourceManager.GetString("FreightTaxableLabel", resourceCulture);
            }
        }
        
        public static string TaxSourceLabel {
            get {
                return ResourceManager.GetString("TaxSourceLabel", resourceCulture);
            }
        }
        
        public static string AmountToCollectLabel {
            get {
                return ResourceManager.GetString("AmountToCollectLabel", resourceCulture);
            }
        }
        
        public static string OrderTotalAmountLabel {
            get {
                return ResourceManager.GetString("OrderTotalAmountLabel", resourceCulture);
            }
        }
        
        public static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        public static string TaxableAmountLabel {
            get {
                return ResourceManager.GetString("TaxableAmountLabel", resourceCulture);
            }
        }
        
        public static string NexusLabel {
            get {
                return ResourceManager.GetString("NexusLabel", resourceCulture);
            }
        }
        
        public static string CalculateTaxesLabel {
            get {
                return ResourceManager.GetString("CalculateTaxesLabel", resourceCulture);
            }
        }
    }
}
